# Clippy config compatible with stable
msrv = "1.70"
cognitive-complexity-threshold = 10
too-many-lines-threshold = 400
too-many-arguments-threshold = 7
type-complexity-threshold = 250
warn-on-all-wildcard-imports = true
disallowed-types = [
    { path = "std::net::TcpStream", reason = "Use QUIC/UDP instead" },
]
